version: "3.8"

services:
  nextjs:
    build:
      context: .
      target: development
    container_name: nextjs_dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    env_file:
      - .env
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    stdin_open: true
    tty: true
    # Uncomment to enable hot reload on Windows/Linux
    # environment:
    #   - WATCHPACK_POLLING=true
